'use client';
import { FormEvent, useEffect, useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api';
type RecordItem={id:number;name:string;email:string;role:string;status:'Active'|'Inactive'};

export default function Home(){
  const [token,setToken]=useState<string|null>(null),[user,setUser]=useState<any>(null),[login,setLogin]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const t=localStorage.getItem('token');if(t)setToken(t);},[]);
  useEffect(()=>{if(token) loadUser();},[token]);
  async function loadUser(){const r=await fetch(`${API}/auth/me`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok){const d=await r.json();setUser(d.user)}else logout()}
  function logout(){localStorage.removeItem('token');setToken(null);setUser(null)}
  if(!token)return <Auth login={login} setLogin={setLogin} setToken={setToken} setUser={setUser} busy={busy} setBusy={setBusy} error={error} setError={setError}/>;
  return <Dashboard token={token} user={user} logout={logout}/>;
}

function Auth({login,setLogin,setToken,setUser,busy,setBusy,error,setError}:any){
 const [name,setName]=useState(''),[email,setEmail]=useState('admin@example.com'),[password,setPassword]=useState('Admin@123');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body=login?{email,password}:{name,email,password};const r=await fetch(`${API}/auth/${login?'login':'register'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Something went wrong');localStorage.setItem('token',d.token);setToken(d.token);setUser(d.user)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="auth-shell"><section className="brand-panel"><div className="logo">F</div><p className="eyebrow">FULL-STACK CRUD</p><h1>FlowBoard</h1><p>Manage your records with a clean, secure and responsive workspace.</p><div className="feature-list"><span>✓ JWT authentication</span><span>✓ REST API</span><span>✓ SQLite persistence</span></div></section><section className="auth-card"><div><p className="eyebrow">WELCOME BACK</p><h2>{login?'Sign in':'Create account'}</h2><p className="muted">{login?'Use your account to access the dashboard.':'Create an account to start managing records.'}</p></div><form onSubmit={submit}>{!login&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} required minLength={2} placeholder="Your name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="••••••••"/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please wait…':login?'Sign in':'Create account'}</button></form><button className="link-btn" onClick={()=>{setLogin(!login);setError('')}}>{login?'New here? Create an account':'Already have an account? Sign in'}</button>{login&&<p className="demo">Demo: admin@example.com / Admin@123</p>}</section></main>
}

function Dashboard({token,user,logout}:{token:string;user:any;logout:()=>void}){
 const [rows,setRows]=useState<RecordItem[]>([]),[search,setSearch]=useState(''),[editing,setEditing]=useState<RecordItem|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(q=''){setLoading(true);try{const r=await fetch(`${API}/records?search=${encodeURIComponent(q)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message);setRows(d.records)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const t=setTimeout(()=>load(search),250);return()=>clearTimeout(t)},[search]);
 async function remove(id:number){if(!confirm('Delete this record?'))return;const r=await fetch(`${API}/records/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});if(r.ok)load(search);else{const d=await r.json();setError(d.message)}}
 return <main className="app"><header><div className="brand"><div className="mini-logo">F</div><div><strong>FlowBoard</strong><small>CRUD workspace</small></div></div><div className="user"><div><strong>{user?.name||'User'}</strong><small>{user?.email}</small></div><button onClick={logout}>Logout</button></div></header><section className="content"><div className="page-head"><div><p className="eyebrow">OVERVIEW</p><h1>Records</h1><p className="muted">Create, edit and manage your data from one place.</p></div><button className="primary add" onClick={()=>{setEditing(null);setOpen(true)}}>＋ Add record</button></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name, email or role…"/><span>{rows.length} records</span></div>{error&&<div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="empty">Loading records…</td></tr>:rows.length===0?<tr><td colSpan={5} className="empty">No records found.</td></tr>:rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>#{r.id}</small></td><td>{r.email}</td><td>{r.role}</td><td><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></td><td><div className="actions"><button onClick={()=>{setEditing(r);setOpen(true)}}>Edit</button><button className="danger" onClick={()=>remove(r.id)}>Delete</button></div></td></tr>)}</tbody></table></div></section>{open&&<RecordModal token={token} item={editing} close={()=>setOpen(false)} saved={()=>{setOpen(false);load(search)}}/>}</main>
}

function RecordModal({token,item,close,saved}:{token:string;item:RecordItem|null;close:()=>void;saved:()=>void}){const [name,setName]=useState(item?.name||''),[email,setEmail]=useState(item?.email||''),[role,setRole]=useState(item?.role||''),[status,setStatus]=useState<'Active'|'Inactive'>(item?.status||'Active'),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const r=await fetch(`${API}/records${item?`/${item.id}`:''}`,{method:item?'PUT':'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({name,email,role,status})});const d=await r.json();if(!r.ok)setError(d.message||'Unable to save');else saved();setBusy(false)}return <div className="overlay"><div className="modal"><div className="modal-head"><div><p className="eyebrow">RECORD</p><h2>{item?'Edit record':'Add record'}</h2></div><button onClick={close}>×</button></div><form onSubmit={submit}><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Role<input value={role} onChange={e=>setRole(e.target.value)} required/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as any)}><option>Active</option><option>Inactive</option></select></label>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':item?'Update record':'Create record'}</button></div></form></div></div>}
